name: build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    env:
      LIBRARY_PATH: '/usr/local/opt/icu4c/lib'

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: install-depedencies
        run: brew update && brew install boost@1.75

      - name: cmake-configure
        run: cmake -B build -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON

      - name: cmake-build
        run: cmake --build build
